# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:

  install:
    sources:
      - package.json
    generates:
      - bun.lock
    cmd: bun install --frozen-lockfile

  test:
    cmd: bun test --coverage

  test:watch:
    interactive: true
    cmd: bun test --watch

  lint:
    sources:
      - ./src/**/*.ts
      - ./test/**/*.ts
    cmd: bunx biome check .

  format:
    sources:
      - ./src/**/*.ts
      - ./test/**/*.ts
    cmd: bunx biome check --write .

  verify:
    requires:
      vars:
      - summary
    cmds:
      - cmd: GITHUB_STEP_SUMMARY={{ .summary }} bunx playwright test
        ignore_error: true
      - diff e2e/snapshots/summary.md {{ .summary }}

  test:all:
    cmds:
      - task: format
      - task: lint
      - task: test
      - task: verify
        vars:
          summary: test-results/summary.md
